--debug constants
DEBUG_PROCS = false
DEBUG_SPELLS = false

IS_DEMO = false
DEMO_END_LEVEL = 11

EXPECTED_SAVE_FIELDS = {
  'level',
  'level_list',
  'loop',
  'gold',
  'units',
  'max_units',
  'passives',
  'shop_item_data',
  'locked_state',
  'reroll_shop',
  'times_rerolled',
  'show_damage_numbers',
  'show_combat_controls',
}

USER_STATS = {}
system.load_stats()

--gold
--note that HoG econ check is in arena.lua (gain_gold)
STARTING_GOLD = 5
GOLD_PER_ROUND = 6
GOLD_FOR_BOSS_ROUND = {10, 15, 20, 25}
INTEREST_AMOUNT = 0.1
MAX_INTEREST = 3

--gold display at end of round
SUM_PLUSGOLD = 0
LAST_PLUSGOLD = 0

STARTING_REROLL_COST = 1
--values should be 1, 2, 3, 4, 5
REROLL_COST = function (times_rerolled)
  -- return math.min(5, times_rerolled + STARTING_REROLL_COST)
  return STARTING_REROLL_COST
end


NUMBER_OF_ROUNDS = 25
BOSS_ROUND_POWER = 1000
BOSS_ROUNDS = {6, 11, 16, 21, 25}

MAX_UNITS = 3

PICK_SECOND_CHARACTER = 5
PICK_THIRD_CHARACTER = 13

RALLY_DURATION = 3

BOSS_MASS = 10
SPECIAL_ENEMY_MASS = 2
REGULAR_ENEMY_MASS = 1
CRITTER_MASS = 0.5

TROOP_MASS = 1
TROOP_KNOCKBACK_MASS = 50

BOSS_DAMPING = 6
SPECIAL_ENEMY_DAMPING = 4
REGULAR_ENEMY_DAMPING = 2
CRITTER_DAMPING = 1
TROOP_DAMPING = 2

LAUNCH_DAMPING = 0.1

-- Friction constants
BOSS_FRICTION = 0.6
ENEMY_FRICTION = 0.6
TROOP_FRICTION = 1

LAUNCH_PUSH_FORCE_ENEMY = 50
LAUNCH_PUSH_FORCE_BOSS = 70

KNOCKBACK_DURATION_BOSS = 1
KNOCKBACK_DURATION_ENEMY = 0.6

BOSS_RESTITUTION = 0.1
SPECIAL_ENEMY_RESTITUTION = 0.5
REGULAR_ENEMY_RESTITUTION = 0.5
CRITTER_RESTITUTION = 0.5

TROOP_RESITUTION = 0.5

TRANSITION_DURATION = 1

ENEMY_CHANCE_TO_TARGET_CRITTER = 0.3

RANDOM_COOLDOWN_VARIANCE = 0.2



LEVEL_TO_TIER = function(level)
  if level < 6 then
    return 1
  elseif level < 11 then
    return 2
  elseif level < 16 then
    return 3
  else
    return 4
  end
end


-- unit constants
MELEE_ATTACK_RANGE = 50

AGGRO_RANGE_BOOST = 100


-- Steering and Movement constants
SEEK_DECELERATION = 1.1
SEEK_WEIGHT = 5.5
SEPARATION_RADIUS = 6
WANDER_RADIUS = 8
WANDER_DISTANCE = 50
WANDER_JITTER = 5


MAX_BOSS_FORCE = 1000
MAX_ENEMY_FORCE = 1000

MAX_TROOP_FORCE = 1000

MAX_V = 100


-- UI constants
SCROLL_SPEED = 5
MIN_SCROLL_LOCATION = -95
MAX_SCROLL_LOCATION = 0

ARENA_TRANSITION_TIME = 3

STARTING_WAVE_COUNTDOWN_DURATION = 0.7
TOTAL_STARTING_WAVE_DELAY = (3 * STARTING_WAVE_COUNTDOWN_DURATION)

get_starting_wave_countdown_value = function(seconds_remaining)
  local value = math.ceil(seconds_remaining / STARTING_WAVE_COUNTDOWN_DURATION)
  return value
end

SELECTED_PLAYER_LIGHTEN = -0.2

LEVEL_TEXT_HOVER_HEIGHT = 100

ITEM_CARD_TEXT_HOVER_HEIGHT_OFFSET = 30

CHARACTER_CARD_WIDTH = 100
CHARACTER_CARD_HEIGHT = 135
CHARACTER_CARD_SPACING = 20

CHARACTER_CARD_ITEM_X = -(CHARACTER_CARD_WIDTH / 2) + 20
CHARACTER_CARD_ITEM_X_SPACING = 30
CHARACTER_CARD_ITEM_Y = (CHARACTER_CARD_HEIGHT / 2) - 40

CHARACTER_CARD_PROC_X = -(CHARACTER_CARD_WIDTH / 2) + 20
CHARACTER_CARD_PROC_X_SPACING = 12
CHARACTER_CARD_PROC_Y = (CHARACTER_CARD_HEIGHT / 2) - 115

ITEM_SLOT_LOWER_BOUND = 190
ITEM_SLOT_DISTANCE = 30

ITEM_SLOT_SIZE = 20

ITEM_CARD_WIDTH = 30
ITEM_CARD_HEIGHT = 45

ACHIEVEMENT_SIZE = 50
ACHIEVEMENT_SPACING = 10
ACHIEVEMENTS_PER_ROW = 4

ACH_CLOSE_BUTTON_SIZE = 20

DAMAGE_NUMBERS_SETTING = {
  'off',
  'enemies',
  'friendlies',
  'all',
}

-- Unit constants

MOVEMENT_RANDOM_TIMER = 5

MOVEMENT_TYPE_SEEK = 'seek'
MOVEMENT_TYPE_RANDOM = 'random'
MOVEMENT_TYPE_FLEE = 'flee'
MOVEMENT_TYPES = {MOVEMENT_TYPE_SEEK, MOVEMENT_TYPE_RANDOM, MOVEMENT_TYPE_FLEE}

-- Spell constants
LASER_FIRE_TYPES = {'target', 'fixed_angle', 'rotating'}

DAMAGE_TYPE_LIGHTNING = 'lightning'
DAMAGE_TYPE_SHOCK = 'shock'
DAMAGE_TYPE_FIRE = 'fire'
DAMAGE_TYPE_BURN = 'burn'
DAMAGE_TYPE_PHYSICAL = 'physical'
DAMAGE_TYPE_POISON = 'poison'
DAMAGE_TYPE_COLD = 'cold'

DAMAGE_TYPES = {DAMAGE_TYPE_LIGHTNING, DAMAGE_TYPE_FIRE, DAMAGE_TYPE_PHYSICAL, DAMAGE_TYPE_POISON, DAMAGE_TYPE_COLD}