require 'enemies/enemy'
require 'enemies/enemy_critter'
require 'enemies/bosses/dragon'
require 'enemies/bosses/heigan'
require 'enemies/bosses/stompy'
require 'enemies/regular/arcspread'
require 'enemies/regular/assassin'
require 'enemies/regular/laser'
require 'enemies/regular/mortar'
require 'enemies/regular/rager'
require 'enemies/regular/seeker'
require 'enemies/regular/shooter'
require 'enemies/regular/spawner'
require 'enemies/regular/spread'
require 'enemies/regular/stomper'
require 'enemies/regular/summoner'
require 'enemies/miniboss/bigstomper'

require 'enemies/static/dragonegg'

require 'enemies/environmental/laser'