require 'enemies/enemy'
require 'enemies/enemy_utils'
require 'enemies/enemy_critter'
require 'enemies/bosses/dragon'
require 'enemies/bosses/heigan'
require 'enemies/bosses/stompy'
require 'enemies/regular/arcspread'
require 'enemies/regular/assassin'
require 'enemies/regular/laser'
require 'enemies/regular/mortar'
require 'enemies/regular/rager'
require 'enemies/regular/seeker'
require 'enemies/regular/shooter'
require 'enemies/regular/spawner'
require 'enemies/regular/spread'
require 'enemies/regular/stomper'
require 'enemies/regular/summoner'
require 'enemies/regular/bomb'
require 'enemies/regular/charger'
require 'enemies/regular/burst'
require 'enemies/regular/boomerang'
require 'enemies/regular/plasma'
require 'enemies/regular/firewall_caster'
require 'enemies/regular/cleaver'
require 'enemies/regular/goblin_archer'
require 'enemies/regular/big_goblin_archer'

require 'enemies/miniboss/bigstomper'

require 'enemies/static/dragonegg'

require 'enemies/environmental/laser'
require 'enemies/environmental/fire_wall'